# Generated by Django 4.2.3 on 2023-07-11 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_nam', models.CharField(default='Patient_nam', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.CharField(max_length=10)),
                ('otp', models.CharField(max_length=6)),
            ],
        ),
        migrations.AlterField(
            model_name='booking',
            name='p_name',
            field=models.CharField(default='Patient_name', max_length=255),
        ),
        migrations.AlterField(
            model_name='doce',
            name='docs_name',
            field=models.CharField(default='Docs_name', max_length=225),
        ),
    ]
